version: 2

before:
  hooks:
    - aube run build

builds:
  - id: foreman
    main: .
    binary: foreman
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^chore:'
      - '^ci:'
      - '^docs:'
      - '^test:'

release:
  draft: true
  replace_existing_artifacts: true
  use_existing_draft: true
